# Stubs for django.http (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.http.cookie import SimpleCookie as SimpleCookie, parse_cookie as parse_cookie
from django.http.request import HttpRequest as HttpRequest, QueryDict as QueryDict, RawPostDataException as RawPostDataException, UnreadablePostError as UnreadablePostError
from django.http.response import BadHeaderError as BadHeaderError, FileResponse as FileResponse, Http404 as Http404, HttpResponse as HttpResponse, HttpResponseBadRequest as HttpResponseBadRequest, HttpResponseForbidden as HttpResponseForbidden, HttpResponseGone as HttpResponseGone, HttpResponseNotAllowed as HttpResponseNotAllowed, HttpResponseNotFound as HttpResponseNotFound, HttpResponseNotModified as HttpResponseNotModified, HttpResponsePermanentRedirect as HttpResponsePermanentRedirect, HttpResponseRedirect as HttpResponseRedirect, HttpResponseServerError as HttpResponseServerError, JsonResponse as JsonResponse, StreamingHttpResponse as StreamingHttpResponse
from django.http.utils import conditional_content_removal as conditional_content_removal
